appPromoConcert/urls.py
from django.urls import path
#from . import views
from django.conf import settings
from django.conf.urls.static import static

from .views import (
    MainView, IndexView, AboutView, PromotorDetalleView, TrackView,
    NuevaReseñaView, ContactView, InterpreteDetalleView, 
    FestivalDetalleView, ReseñasView, ContactView, TestBaseView
)



#urlpatterns = [
#    path('', views.index, name='index'),
#    path('about/', views.about, name='about'),
#    path('promotor/<int:promotor_id>/', views.promotor_detalle, name='promotor_detalle'),
#
#    path('contact/',views.contact, name='contact'),
#    path('interprete/<int:id>/', views.interprete_detalle, name='interprete_detalle'), 


#    path('track/',views.track, name='track'),
#    path('track/<int:id>/', views.festival_detalle, name='festival_detalle'),
    
#    path('main/',views.main, name='main'),
#    path('base/', views.test_base, name='test_base'),

#    path('reseñas/', views.reseñas, name='reseñas'),
#    path('reseñas/nueva/', views.nueva_reseña, name='nueva_reseña'),

#]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)



urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('about/', AboutView.as_view(), name='about'),
    path('promotor/<int:pk>/', PromotorDetalleView.as_view(), name='promotor_detalle'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('interprete/<int:pk>/', InterpreteDetalleView.as_view(), name='interprete_detalle'), 
    path('track/', TrackView.as_view(), name='track'),
    path('track/<int:pk>/', FestivalDetalleView.as_view(), name='festival_detalle'),
    path('main/', MainView.as_view(), name='main'),
    path('base/', TestBaseView.as_view(), name='test_base'),
    path('reseñas/', ReseñasView.as_view(), name='reseñas'),
    path('reseñas/nueva/', NuevaReseñaView.as_view(), name='nueva_reseña'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

empresaPromoConcert/urls.py
from django.contrib import admin
from django.urls import path, include

#from django.conf.urls.i18n import i18n_patterns
#from django.views.i18n import set_language

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('appPromoConcert.urls')),
    #path('set_language/', set_language, name='set_language'),

]

#urlpatterns += i18n_patterns(
#    path('',include('appPromoConcert.urls')),
   # path('set_language/', set_language, name='set_language'),
#)

appPromoConcert/models.py
from django.db import models

# Create your models here.

class PromotorMusical(models.Model):
    nombre = models.CharField(max_length=100)
    descripcion = models.TextField()
    pais_origen = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre
    
    def get_imagen_promotor(self):
        return f'img/promotores/{self.id}.png'
    
class Festival(models.Model):
    nombre = models.CharField(max_length=100)
    fecha_inicio = models.DateField()
    fecha_fin = models.DateField()
    ubicacion = models.CharField(max_length=200)              #promotor.festivales.all()
    promotor = models.ForeignKey(PromotorMusical, on_delete=models.CASCADE, related_name='festivales')    

    def __str__(self):
        return self.nombre
    
    def get_imagen_festival(self):
        return f'img/festivales/{self.id}.png'
    
class Interprete(models.Model):
    nombre = models.CharField(max_length=100)
    genero = models.CharField(max_length=50)
    pais_origen = models.CharField(max_length=100)   #festival.interpretes.all()
    festivales = models.ManyToManyField(Festival, related_name='interpretes')

    def __str__(self):
        return self.nombre
    
    def get_imagen_interprete(self):
        return f'img/interpretes/{self.id}.png'
    
#reseñas
class Reseña(models.Model):
    nombre = models.CharField(max_length=100)
    festival = models.ForeignKey('Festival', on_delete=models.CASCADE, related_name='reseñas')
    comentario = models.TextField()
    fecha = models.DateTimeField(auto_now_add=True)
    calificacion = models.IntegerField(default=0)  # Valor entre 1 y 5


    def __str__(self):
        return f"Reseña de {self.nombre} sobre {self.festival.nombre}"
    
    #para convertir calificacion en estrellas
    def estrellas(self):
        return ['★' if i < self.calificacion else '☆' for i in range(5)]

appPromoConcert/forms.py
from django import forms
from .models import Reseña, Festival

class ReseñaForm(forms.ModelForm):
    CALIFICACIONES = [
        (1, '★☆☆☆☆'),
        (2, '★★☆☆☆'),
        (3, '★★★☆☆'),
        (4, '★★★★☆'),
        (5, '★★★★★'),
    ]

    calificacion = forms.ChoiceField(
        choices=CALIFICACIONES,
        widget=forms.RadioSelect,  # Usa radio buttons
        label="Calificación"
    )

    class Meta:
        model = Reseña
        fields = ['nombre', 'festival', 'comentario', 'calificacion']

appPromoConcert/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import render, get_object_or_404, redirect
from .models import PromotorMusical, Festival, Interprete, Reseña
from django.db.models import OuterRef,Subquery,Max
from .forms import ReseñaForm

from django.views.generic import TemplateView
from django.views.generic import ListView
from django.db.models import OuterRef, Subquery
from django.views.generic import DetailView
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy
from .models import Reseña
from .forms import ReseñaForm
#from django.utils import translation
#from django.http import HttpResponseRedirect
#from django.urls import reverse 

# Create your views here.
#aqui hay que "diseñar" las páginas
#y luego en urls.py hay que añadirle dirección a cada pagina

#MAIN-------------------------------------------------------------------------------------

#funcion:
#def main(request):
#   return render(request, 'appPromoConcert/main.html')

#clase:
class MainView(TemplateView):
    template_name = 'appPromoConcert/main.html'

#INDEX--------------------------------------------------------------------------------------

#Funcion:
#def index(request):
#
#   subconsulta = Festival.objects.filter(promotor=OuterRef('promotor')).order_by('-fecha_inicio').values('id')[:1]
#
#    # Obtener un festival por cada promotor (el más reciente como ejemplo)
#    festivales_por_promotor = Festival.objects.filter(id__in=Subquery(subconsulta))

#    for festival in festivales_por_promotor:
#        festival.imagen_url = f'img/festivales/{festival.id}.png'


#    return render(request, 'appPromoConcert/index.html', {
#        'festivales': festivales_por_promotor,
#    })

#Clase:
class IndexView(ListView):
    model = Festival
    template_name = 'appPromoConcert/index.html'
    context_object_name = 'festivales'

    def get_queryset(self):
       #coger festival más reciente por cada promotor
       subconsulta = Festival.objects.filter(promotor=OuterRef('promotor')).order_by('-fecha_inicio').values('id')[:1]
       return Festival.objects.filter(id__in=Subquery(subconsulta))
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        #coger cada imagen por festival
        for festival in context['festivales']:
            festival.imagen_url = f'img/festivales/{festival.id}.png'
        return context

#PROMOTORES--------------------------------------------------------------------------------------

#funcion:
#def about(request):
#    promotores = PromotorMusical.objects.all()
#    return render(request, 'appPromoConcert/about.html', {'promotores' : promotores})

#Clase:
class AboutView(ListView):
    model = PromotorMusical
    template_name = 'appPromoConcert/about.html'
    context_object_name = 'promotores'

#PROMOTOR DETALLE--------------------------------------------------------------------------------------

#funcion: 
#def promotor_detalle(request, promotor_id):
#    promotor = get_object_or_404(PromotorMusical, pk=promotor_id)
#    festivales = promotor.festivales.all()
#    return render(request, 'appPromoConcert/promotor_detalle.html', {'promotor':promotor, 'festivales': festivales})


#clase:
class PromotorDetalleView(DetailView):
    model = PromotorMusical
    template_name = 'appPromoConcert/promotor_detalle.html'
    context_object_name = 'promotor'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['festivales'] = self.object.festivales.all()
        return context

#FESTIVALES--------------------------------------------------------------------------------------

#funcion:
#def track(request):
#    festivales = Festival.objects.all()
    
#    context = {
#        'festivales': festivales,
#    }
#    return render(request, 'appPromoConcert/track.html', context)

#clase:
class TrackView(ListView):
    model = Festival
    template_name = 'appPromoConcert/track.html'
    context_object_name = 'festivales'


#FESTIVAL DETALLE--------------------------------------------------------------------------------------

#funcion:
#def festival_detalle(request, id):
#    festival = get_object_or_404(Festival, id=id)
#    interpretes = festival.interpretes.all()
#    return render(request, 'appPromoConcert/festival_detalle.html', {'festival': festival, 'interpretes': interpretes})

#clase:
class FestivalDetalleView(DetailView):
    model = Festival
    template_name = 'appPromoConcert/festival_detalle.html'  # Nombre del template que mostrarás
    context_object_name = 'festival'  # Este es el nombre con el que accederás al objeto en el template

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        festival = self.get_object()  # Obtén el festival actual
        context['interpretes'] = festival.interpretes.all()  # Agrega los intérpretes al contexto
        return context


#INTERPRETES--------------------------------------------------------------------------------------

#funcion:
#def contact(request):
#    interpretes = Interprete.objects.all()
#    return render(request, 'appPromoConcert/contact.html', {'interpretes': interpretes})

#clase:
class InterpreteDetalleView(DetailView):
    model = Interprete
    template_name = 'appPromoConcert/interprete_detalle.html'
    context_object_name = 'interprete'

#INTERPRETE DETALLE--------------------------------------------------------------------------------------

#funcion:
#def interprete_detalle(request, id):
#    interprete = get_object_or_404(Interprete, id=id)  
#    return render(request, 'appPromoConcert/interprete_detalle.html', {'interprete': interprete})

#clase:
class ContactView(ListView):
    model = Interprete
    template_name = 'appPromoConcert/contact.html'
    context_object_name = 'interpretes'

#BASE--------------------------------------------------------------------------------------

#funcion:
#def test_base(request):
#    return render(request, 'base.html')


#clase:
class TestBaseView(TemplateView):
    template_name = 'base.html'


#RESEÑAS----------------------------------------------------------------------------------------------

#funcion:
#def reseñas(request):
#    reseñas = Reseña.objects.all().order_by('-fecha')
#    for reseña in reseñas:
#        reseña.range_calificacion = range(reseña.calificacion)
#        reseña.range_estrellas_vacias = range(5 - reseña.calificacion)
#    return render(request, 'appPromoConcert/reseñas.html', {'reseñas': reseñas})

#clase:
class ReseñasView(ListView):
    model = Reseña
    template_name = 'appPromoConcert/reseñas.html'
    context_object_name = 'reseñas'
    ordering = ['-fecha']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Añadir rangos de estrellas para visualización
        for reseña in context['reseñas']:
            reseña.range_calificacion = range(reseña.calificacion)
            reseña.range_estrellas_vacias = range(5 - reseña.calificacion)
        return context

#NUEVA RESEÑA-------------------------------------------------------------------------------

#funcion:
#def nueva_reseña(request):
#    if request.method == 'POST':
#        form = ReseñaForm(request.POST)
#        if form.is_valid():
#            form.save()
#            return redirect('reseñas')
#    else:
#        form = ReseñaForm()
#    return render(request, 'appPromoConcert/nueva_reseña.html', {'form': form})

#clase:
class NuevaReseñaView(CreateView):
    model = Reseña
    form_class = ReseñaForm
    template_name = 'appPromoConcert/nueva_reseña.html'
    success_url = reverse_lazy('reseñas')


#Traduccion

#def set_language(request):
#    user_language = request.POST.get('language', 'en') 
#    translation.activate(user_language)
#    request.session[translation.LANGUAGE_SESSION_KEY] = user_language
#    print(f'Idioma cambiado a: {user_language}')
#    return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/')) 

appPromoConcert/templates/appPromoConcert/about.html
{% extends 'base.html' %}

{% block content %}
{% load static %}

   <!-- bradcam_area  -->
    <div class="bradcam_area breadcam_bg_2">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text text-center">
                        <h3>Promotores Musicales</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->
 
<!-- Lista de promotores -->
<div class="container mt-5"> 
    <div class="row">
        {% for promotor in promotores %}
        <div class="col-xl-4 col-md-6 mb-4">
            <div class="about_info">
                <img src="{% static promotor.get_imagen_promotor %}" alt="{{ promotor.nombre }}" height="150">
                <p><strong>País:</strong> {{ promotor.pais_origen }}</p>

                <!-- Botón Ver Más -->
                <a href="{% url 'promotor_detalle' promotor.id %}" class="btn btn-primary">Ver Más</a>
            </div>
        </div>
        {% endfor %}
    </div>
</div>



{% endblock %}

appPromoConcert/templates/appPromoConcert/contact.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

<!-- bradcam_area -->
<div class="bradcam_area breadcam_bg_4 mb-5">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div class="bradcam_text text-center">
                    <h3>Intérpretes</h3>
                </div>
            </div>
        </div>
    </div>
</div>
<!--/ bradcam_area -->

<!-- Lista de intérpretes -->
<div class="container">
    <h2 class="mb-4">Todos los Artistas</h2>
    <div class="row">
        {% for interprete in interpretes %}
        <div class="col-xl-4 col-md-6 mb-4 d-flex align-items-stretch">
            <div class="interprete_item text-center border p-3 rounded shadow-sm">
                <div class="thumb mb-3">
                    <img src="{% static interprete.get_imagen_interprete %}" alt="{{ interprete.nombre }}" class="img-fluid rounded interprete-img">
                </div>
                <div class="info">
                    <h4 class="mb-2">{{ interprete.nombre }}</h4>
                    <p>{{ interprete.genero }}</p>
                    <a href="{% url 'interprete_detalle' interprete.id %}" class="boxed-btn">Ver más</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

appPromoConcert/templates/appPromoConcert/festival_detalle.html
{% extends 'base.html' %}

{% block content %}
{% load static %}


<!-- bradcam_area  -->
<div class="bradcam_area breadcam_bg_3 mb-5">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div class="bradcam_text text-center">
                    <h3>{{festival.nombre}}</h3>
                </div>
            </div>
        </div>
    </div>
</div>
<!--/ bradcam_area  -->

<div class="container mb-5">
    <h2>{{ festival.nombre }}</h2>
    <div class="festival-detail">
        <div class="row mb-5">
            <div class="col-xl-6 mb-4">
                <div class="festival-image">
                    <img src="{% static festival.get_imagen_festival %}" alt="{{ festival.nombre }}" class="img-fluid">
                </div>
            </div>
            <div class="col-xl-6">
                <div class="festival-info">
                    <p><strong>Fecha de Inicio:</strong> {{ festival.fecha_inicio }}</p>
                    <p><strong>Fecha de Fin:</strong> {{ festival.fecha_fin }}</p>
                    <p><strong>Ubicación:</strong> {{ festival.ubicacion }}</p>
                    <p><strong>Promotor musical: <a href="{% url 'promotor_detalle' festival.promotor.id %}" class="custom-link">{{ festival.promotor }}</a></strong></p>
                    
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-xl-12">
                <h3 class="mb-4">Intérpretes</h3>
                <ul class="mb-4">
                    {% for interprete in interpretes %}
                        <!--<li>{{ interprete.nombre }} - {{ interprete.genero }} ({{ interprete.pais_origen }})</li>-->
                        <li><a href="{% url 'interprete_detalle' interprete.id %}" class="custom-link">{{ interprete.nombre }} - {{ interprete.genero }} ({{ interprete.pais_origen }})</a></li>
                     {% empty %}
                         <li>No hay intérpretes confirmados para este festival todavía.</li>
                    {% endfor %}
                </ul>
                <a href="{% url 'track' %}" class="btn btn-primary">Volver a los festivales</a>

            </div>
        </div>
    </div>
</div>
{% endblock %}

appPromoConcert/templates/appPromoConcert/index.html
{% extends 'base.html' %}

{% block content %}
{% load static %}

    <!-- slider_area_start -->
    <div class="slider_area">
        <div class="single_slider  d-flex align-items-center slider_bg_1 overlay2">
            <div class="container">
                <div class="row">
                    <div class="col-xl-12">
                        <div class="slider_text text-center ">
                            <h3>PROMO CONCERT </h3>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- slider_area_end -->

    <!-- promotor principal  -->
    <div class="about_area">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-xl-5 col-md-6">
                    <div class="about_thumb">
                        <img class="img-fluid" src="{% static 'img/about/about_1.png' %}" alt="">
                    </div>
                </div>
                <div class="col-xl-7 col-md-6">
                    <div class="about_info">
                        <h3>Live Nation</h3>
                        <p>Live Nation Entertainment es la promotora de conciertos y festivales más famosa del mundo, reconocida por su impacto global en la industria musical. Con una presencia en más de 40 países, ha organizado algunos de los festivales más icónicos, como Lollapalooza, Rock Werchter, Reading & Leeds, y Isle of Wight Festival. Su liderazgo y asociación con los artistas más grandes del planeta la posicionan como la referencia principal en entretenimiento en vivo.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ about_area  -->

    <!-- Festivales por Promotor -->
<div class="container mb-5">
    <h2 class="mb-4">Festivales por Promotor</h2>
    {% for festival in festivales %}
    <div class="row align-items-center mb-5">
        <div class="col-xl-8 col-md-8">
            <!-- Imagen del festival -->
            <div class="thumb mb-3">
               <img src="{% static festival.get_imagen_festival %}" alt="{{ festival.nombre }}" class="img-fluid">                
            </div>
            <div class="audio_name">
            <!-- Nombre del promotor -->
                <h4>{{ festival.promotor.nombre }}</h4>
            <!-- Nombre y fechas del festival -->
                <h5>{{ festival.nombre }}</h5>
                <p>Fecha de inicio: {{ festival.fecha_inicio }}</p>
                <p>Fecha de fin: {{ festival.fecha_fin }}</p>
                <div class="music_btn">
                    <a href="{% url 'festival_detalle' festival.id %}" class="boxed-btn">Ver más</a>
                </div>
            
            </div>
        </div>
    </div>
     
    {% endfor %}
</div>

    
{% endblock %}
    


  

appPromoConcert/templates/appPromoConcert/interprete_detalle.html
{% extends 'base.html' %}

{% block content %}
{% load static %}

<!-- bradcam_area -->
<div class="bradcam_area breadcam_bg_4 mb-5">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div class="bradcam_text text-center">
                    <h3>{{ interprete.nombre }}</h3>
                </div>
            </div>
        </div>
    </div>
</div>
<!--/ bradcam_area -->

<!-- Detalle del intérprete -->
<div class="container mb-5">
    <div class="row align mb-5">
        <div class="col-xl-4 col-md-5 mb-4">
            <div class="interprete_thumb">
                <img src="{% static interprete.get_imagen_interprete %}" alt="{{ interprete.nombre }}" class="img-fluid">
            </div>
        </div>
        <div class="col-xl-8 col-md-7">
            <div class="interprete_info">
                <h4 class="mb-4">{{ interprete.nombre }}</h4>
                <p><strong>Género:</strong> {{ interprete.genero }}</p>
                <p><strong>País de origen:</strong> {{ interprete.pais_origen }}</p>

                <h5 class="mb-3">Festivales en los que cantará:</h5>
                <ul class="mb-4">
                    {% for festival in interprete.festivales.all %}
                        <li><a href="{% url 'festival_detalle' festival.id %}">{{ festival.nombre }} ({{ festival.fecha_inicio }} - {{ festival.fecha_fin }})</a></li>
                    {% endfor %}
                </ul>
                <a href="{% url 'contact' %}" class="btn btn-primary">Volver a los intérpretes</a>

            </div>
        </div>
    </div>
</div>

{% endblock %}

appPromoConcert/templates/appPromoConcert/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Your Page Title Here</title>
    <style>
        img {
            margin: 0 auto;
            display: block;
            margin-top: 20%;
        }
    </style>
</head>
<body>
    <a href="https://colorlib.com/wp/templates/">
        <img src="https://colorlib.com/wp/wp-content/uploads/sites/2/colorlib-push-logo.png" alt="Colorlib logo">
    </a>
    <h1 style="text-align:center;">Thank you for using our template!</h1>
    <p style="text-align:center;">For more awesome templates please visit <strong><a href="https://colorlib.com/wp/templates/">Colorlib</a></strong>.</p>
    <br>
    <p style="text-align:center; color:red;">
        <strong>Copyright information for the template can't be altered/removed unless you purchase a license.</strong>
    </p>
    <p style="text-align:center;">
        <strong>Removing copyright information without the license will result in suspension of your hosting and/or domain name(s).</strong>
    </p>
    <p style="text-align:center;">
        <strong>More information about the license is available <a href="https://colorlib.com/wp/licence/">here</a></strong>.</p>
</body>
</html>

appPromoConcert/templates/appPromoConcert/nueva_reseña.html
{% extends 'base.html' %}

{% block content %}

<!-- bradcam_area  -->
<div class="bradcam_area breadcam_bg_5">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div class="bradcam_text text-center">
                    <h3>Nueva Reseña</h3>
                </div>
            </div>
        </div>
    </div>
</div>
<!--/ bradcam_area  -->

<div class="container">
    <h2>Escribir una reseña</h2>
    <form method="post">
        {% csrf_token %}
        
        <!-- Nombre -->
        <div class="form-group">
            <label for="id_nombre">Nombre:</label>
            {{ form.nombre }}
        </div>

        <!-- Festival -->
        <div class="form-group">
            <label for="id_festival">Festival:</label>
            {{ form.festival }}
        </div>

        <!-- Texto -->
        <div class="form-group">
            <label for="id_comentario">Comentario:</label>
            {{ form.comentario }}
        </div>

        <!-- Calificación -->
        <div class="calificacion">
            <input type="radio" id="star5" name="calificacion" value="5">
            <label for="star5" title="5 estrellas">★</label>
            <input type="radio" id="star4" name="calificacion" value="4">
            <label for="star4" title="4 estrellas">★</label>
            <input type="radio" id="star3" name="calificacion" value="3">
            <label for="star3" title="3 estrellas">★</label>
            <input type="radio" id="star2" name="calificacion" value="2">
            <label for="star2" title="2 estrellas">★</label>
            <input type="radio" id="star1" name="calificacion" value="1">
            <label for="star1" title="1 estrella">★</label>
        </div>
        

        <!-- Botón de envío -->
        <button type="submit" class="btn btn-success mb-5">Enviar</button>
        <a href="{% url 'reseñas' %}" class="btn btn-secondary mb-5">Volver</a>
    </form>
</div>
{% endblock %}

appPromoConcert/templates/appPromoConcert/promotor_detalle.html
{% extends 'base.html' %}

{% block content %}
{% load static %}

<!-- bradcam_area  -->
<div class="bradcam_area breadcam_bg_2 mb-5">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div class="bradcam_text text-center">
                    <h3>{{promotor.nombre}}</h3>
                </div>
            </div>
        </div>
    </div>
</div>
<!--/ bradcam_area  -->

<!-- Información del promotor -->
<div class="container mb-5">
    <div class="row mb-5">
        <div class="col-xl-6 mb-4">
            <div class="promotor-image">
                <img src="{% static promotor.get_imagen_promotor %}" alt="{{ promotor.nombre }}" class="img-fluid">
            </div>
        </div>
        <div class="col-xl-6">
            <div class="promotor-info">
                <h4>{{ promotor.nombre }}</h4>
                <p>{{ promotor.descripcion }}</p>
                <p><strong>País de Origen:</strong> {{ promotor.pais_origen }}</p>
            </div>
        </div>
    </div>
    <!-- Lista de festivales -->
    <div class="row mb-5">
        <div class="col-xl-8 col-md-6">
            <h5>Festivales Organizados:</h5>
            <ul class="mb-4">
                {% for festival in festivales %}
                    <li>
                        <a href="{% url 'festival_detalle' festival.id %}">{{ festival.nombre }} ({{ festival.fecha_inicio }} - {{ festival.fecha_fin }})</a>
                    </li>
                {% empty %}
                    <li><p>No hay festivales organizados por este promotor.</p></li>
                {% endfor %}
            </ul>
            <a href="{% url 'about' %}" class="btn btn-primary">Volver a los promotores</a>
        </div>
    </div>
</div>

{% endblock %}

appPromoConcert/templates/appPromoConcert/reseñas.html
{% extends 'base.html' %}

{% block content %}

<!-- bradcam_area  -->
<div class="bradcam_area breadcam_bg_5">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div class="bradcam_text text-center">
                    <h3>Reseñas</h3>
                </div>
            </div>
        </div>
    </div>
</div>
<!--/ bradcam_area  -->


<div class="container mb-5">
    <a href="{% url 'nueva_reseña' %}" class="btn btn-primary mb-5">Escribir una reseña</a>
    <div class="list-group">
        {% for reseña in reseñas %}
        <div class="list-group-item">
            <h4>{{ reseña.nombre }}</h4>
            <h5>Festival: {{ reseña.festival.nombre }}</h5> 
            <div class="estrellas">
                {% for i in reseña.range_calificacion %}
                    <i class="fa fa-star"></i>  <!-- Estrella llena -->
                {% endfor %}
                {% for i in reseña.range_estrellas_vacias %}
                    <i class="fa fa-star-o"></i>  <!-- Estrella vacía -->
                {% endfor %}
            </div>
            <p>{{ reseña.comentario }}</p>
            <small>{{ reseña.fecha|date:"d M Y H:i" }}</small>
        </div>
        
        {% endfor %}
    </div>
</div>
{% endblock %}

appPromoConcert/templates/appPromoConcert/track.html
{% extends 'base.html' %}

{% block content %}
{% load static %}

<!-- bradcam_area -->
<div class="bradcam_area breadcam_bg_3 mb-5">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div class="bradcam_text text-center">
                    <h3>Festivales</h3>
                </div>
            </div>
        </div>
    </div>
</div>
<!--/ bradcam_area -->

<div class="container mb-5">
    <h2 class="mb-4">Todos los Festivales</h2>
    {% for festival in festivales %}
    <div class="row align-items-center mb-5">
        <div class="col-xl-8 col-md-8">
            <div class="thumb mb-3">
                <img src="{% static festival.get_imagen_festival %}" alt="{{ festival.nombre }}" class="img-fluid">
            </div>
            <div class="audio_name">
                <div class="name">
                    <h4 class="mb-2">{{ festival.nombre }}</h4>
                    <p>{{ festival.fecha_inicio }}</p>
                </div>
            </div>
        </div>
        <div class="col-xl-3 col-md-4 text-md-right text-center mt-3 mt-md-0">
            <div class="music_btn">
                <a href="{% url 'festival_detalle' festival.id %}" class="boxed-btn">Ver más</a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}